name: Terraform (Dev)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/**"
  push:
    branches: ["main"]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "Repo root:"
          pwd
          echo "TF_WORKDIR='${{ vars.TF_WORKDIR }}'"
          echo "List repo root:"
          ls -la
          echo "List infra/terraform:"
          ls -la infra || true
          ls -la infra/terraform || true
          ls -la infra/terraform/envs || true
          ls -la infra/terraform/envs/dev || true
          echo "List TF_WORKDIR:"
          ls -la "${{ vars.TF_WORKDIR }}" || true

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ vars.TF_WORKDIR }}
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: ${{ vars.TF_WORKDIR }}
        run: terraform validate

      - name: Terraform plan (PR)
        if: github.event_name == 'pull_request'
        working-directory: ${{ vars.TF_WORKDIR }}
        run: terraform plan -no-color -input=false

      - name: Terraform apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ${{ vars.TF_WORKDIR }}
        run: terraform apply -auto-approve -input=false

